version: "3"

# environment variables are defined in the file local.env
# My current knowledge is, that this file can only be passed to
# docker-compose as .env. Hence, please make it a symbolic link:
# ln -s local.env .env
#
# Currently defined are:
# ${DATADIR} - the data directory where the underlying data can be found
# ${BACKENDPORT}  - outside port for the backend
# ${ELASTICPORT}  - outside port for the elastic search

services:

  frontend:
    build: ./frontend
    networks:
      - net
    ports:
      - ${FRONTENDPORT}:80
    logging:
      driver: json-file
      options:
        max-size: 10m

  backend:
    build: .
    volumes:
      - ${DATADIR}/:/data/
    networks:
      - net 
    logging:
      driver: json-file
      options:
        max-size: 10m
    # ports:
    #   - ${BACKENDPORT}:3330

  es:
    build: ./elasticsearch
    networks:
      - net
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ${DATADIR}/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - net
    security_opt:
      - label:user:root
      - label:role:root
    logging:
      driver: json-file
      options:
        max-size: 10m
    # ports:
    #   - ${ELASTICPORT}:9200      
networks:
  net:
    driver: bridge
