version: "3"

services:

  backend:
    build: .
    volumes:
      - /data/vec2sparql/:/data/
    networks:
      - net 

  frontend:
    build: ./frontend
    networks:
      - net
    ports:
      - 85:80

  es:
    build: ./elasticsearch
    networks:
      - net
      
networks:
  net:
    driver: bridge
